### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by testack18** [Tms-bodnar/MMM-BKK-Futar#1]
Szia,

Sajnos nem vagyok otthon a GitHubban, így kérlek nézd el nekem, hogy ilyen formában veszem fel Veled a kapcsolatot. Sajnos nem találtam privát üzenet funkciót.

Tök szuper a progid! Pont ez kell nekem is. Három apróságot szeretnék visszajelezni:
- ha minden igaz, a telepítési leírásból kimaradt az `npm install` parancs
- ha csak 1 megállót adsz meg, akkor a stopTimes nem küld vissza stopId-t. Ezt én az alábbi módon orvosoltam:
`stopNameId = stopTimes[i].stopId ? stopTimes[i].stopId : body.data.entry.stopId;`
- továbbá módosítottam a saját klónban (nem tudom, jó terminológiát használok e?), hogy a predictedDepartureTime-ot is vegye figyelembe ott, ahol van:
`var departureTimeInMillis = stopTimes[i].predictedDepartureTime ? stopTimes[i].predictedDepartureTime * 1000: stopTimes[i].departureTime * 1000;`

Én mondjuk nem vagyok fejlesztő, lehet hülyeséget csináltam a fentiekkel, de hátha hasznosnak tartod.

Illetve szeretném a segítséged/tapasztalatod kérni, ha lehet. Már meg is építetted a tükröd, vagy még csak a software-es résznél tartasz? Én a hardware-nél elakadtam. Nem tudod véletlenül, hogy kishazánkban hol lehet megfelelő üveget/plexit/fóliát beszerezni?

Előre is köszi! Szuper, hogy itthonról is találtam forrást!

Üdv,
-Gábor-

**Comment by tmsBodnar** [comment]
Szia Gábor!
Örülök, hogy hasznos a modulom :-)
Én sem vagyok főállású fejlesztő (még), úgyhogy minden issuenak örülök.
A telepítést javítottam, köszi.
A modul írása közben azt tartottam szem előtt, amire nekem volt szükségem, így nem nagyon foglalkoztam a predictedDepartureTime-al, mert az én két megállómban gyakoriak a járatok, így nem tartottam lényegesnek.
Egyébként egy megállót is kezelnie kellene, ha a configban egy megállót írsz a szögletes zárójelek közé, mert úgy egy elemű tömnek kellene kezelnie.
```
config: {
            stopNumber:  ["BKK_F03308"],
        }
```
 Úgy emlékszem, nekem kezelte így is. Sajnos most nem tudom lepróbálni, mert szétszedtem, hogy elkészítsem a dobozát.
Köszi a javításokat, küldd el a kódod, vagy csinálj egy pull requestet, és befrissítem vele, bekommentelem a kódrészeidet, és lezárom az issuet.

A szoftverrel készen vagyok, de nem tükröt csinálok, csak egy infoboard-ot, úgyhogy a detektívtükörrel kapcsolatbannem tudok segíteni. Fa dobozba fogom tenni, és beépítek pár kiegészítőt, (mikrofon, hangszóró, kamera, néhány szenzor), ezek kezelésére egy plexi előlapom lesz, rajta a gombok és potméterek helye, ill. a néhány egyéb szükséges nyílás. Sajnos most 3 hétig pihentetnem kell egyéb dolgaim miatt, de ha készen lesz, csinálok róla egy bemutatót a blogomon.
(www.okosnotesz.hu)

Üdv: Tamás

**Comment by testack18** [comment]
Szia Tamás,

Igen, a kódod le is kezeli frankón az 1 elemű tömböt, nem Nálad van a hiba. Egyszerűen a BKK nem ugyan olyan formátumban adja vissza a választ ha csak 1 megállóra kéred le. Egyszerűen nem jön tőlük vissza stopId a stopTimes tömbben. Majd néz meg, lehet én bénáztam valamit. Ha így van, kérlek írd meg, hogy mit nézek be. Nálam így néz ki a stopTimes lista ha csak egy megállót nézek:
`"stopTimes": [
        {
          "stopHeadsign": "Örs vezér tere M H",
          "arrivalTime": 1522695780,
          "departureTime": 1522695780,
          "predictedArrivalTime": 1522695856,
          "predictedDepartureTime": 1522695856,
          "tripId": "BKK_B777051362",
          "serviceDate": "20180402"
        },
        {
          "stopHeadsign": "Helikopter lakópark",
          "arrivalTime": 1522696200,
          "departureTime": 1522696200,
          "predictedArrivalTime": 1522696226,
          "predictedDepartureTime": 1522696226,
          "tripId": "BKK_B78219217",
          "serviceDate": "20180402"
        },
...
...
`
Ne haragudj, de a kódodat eléggé átírtam a saját igényeimnek megfelelően, és jelenleg félállapotban van. Természetesen az internetre nem tervezem publikálni, és szívesen átküldöm, amint olyan állapotba kerül, hogy nem csupa hibát dob. :)
Amit én beletettem: Google geolocation alapján pozíció lekérése, opció, hogy cím vagy bekonfigolt koordináták alapján is megtalálja a közeli megállókat. Ebből a geolocation megy, a többi még félállapotban van. Inkább elküldeném, ha megvan, nem vagyok sajnos otthon a githubban és a pull requestben, nem tudom mi fán terem.

Az issuet részemről nyugodtan lezárhatod, csak szerettem volna felvenni veled a kapcsolatot, mert tökre örültem, hogy találtam itthonról valakit, aki pont ezt a modult már elkezdte.

Átfutottam a blogodat, de így húsvét hétfő este még csak a főcímeket. Érdekes dolgok lesznek, kicsit később alaposabban szemügyre veszem, főleg az Alexás részt. :) 
(Valamiért nekem a posztodba írt URL-t ha rá kattintok, a github címe után fűzve nyitja meg az új lapot, így az csak akkor él, ha kézzel beírom a böngészőbe. Nem tudom, lehet csak nálam van a para.)

Minden esetre még egyszer, tökre örülök, hogy rátaláltam erre a modulra! Tök szuper! 

Üdv,
Gábor

**Comment by tmsBodnar** [comment]
Hahó Gábor!
Igazából ha egy megállót kérdezel le, szerintem azért nem adja vissza a stopId-t, mert már tudod, hiszen a lekérdezésben megadtad.
Ha készen vagy, megnézném, érdekel a megoldásod :-)
És természetesen publikálhatod is, nincs akadálya, MIT licensz.
Üdv. Tamás
